defaultTasks 'clean','test'

buildscript {
    repositories {
        mavenLocal()
    }
}

apply plugin: 'java'

dependencies {
    testImplementation libs.bundles.cucumber
    testImplementation libs.bundles.testing
    testImplementation libs.bundles.appium
    testImplementation libs.bundles.commons
}

repositories {
    mavenCentral()
}

test {
    testLogging.showStandardStreams = true
}

test {
    testLogging.showStandardStreams = true
    systemProperty "server", System.getProperty("server")
    systemProperty "username", System.getProperty("username")
    systemProperty "password", System.getProperty("password")
    systemProperty "commit", System.getProperty("commit")
}

gradle.startParameter.continueOnFailure = true
